// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:ad11e4c4-217a-4cd0-8c2f-4be972a82f0e',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_jUsEumFTp',
  aws_user_pools_web_client_id: '4098c8j1lqo9qehh4mu5j4n0e4',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://u3n2sdinq5cb7bufcygp743dni.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-4tjosn7myvgvjl37u6tdcmq7w4',
  aws_content_delivery_bucket: 'chime-vc-agentassist-20200303170349-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url:
    'http://chime-vc-agentassist-20200303170349-hostingbucket-dev.s3-website-us-east-1.amazonaws.com',
};

export default awsmobile;
