/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:da548ad1-04e6-4632-9a07-1442e38c4763",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LXVMQXoVD",
    "aws_user_pools_web_client_id": "2d8pv68eepg1e0brtr0f67pi7u",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hyrd63b2frd2bktcsiclvpzkii.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sk4dq4wjzjbl3lxsxzltgd2ja4",
    "aws_content_delivery_bucket": "chime-vc-agentassist-083981752084-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://chime-vc-agentassist-083981752084-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
